// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5bIXmThn_waxcS6H95FB3Kzn5ODqLT8I',
    appId: '1:704124013106:web:90a5b9703fd547dd2c4a2b',
    messagingSenderId: '704124013106',
    projectId: 'abhayam-iej12s',
    authDomain: 'abhayam-iej12s.firebaseapp.com',
    storageBucket: 'abhayam-iej12s.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjCRzfPELEtkyunaBTQp45Vl502Csclp8',
    appId: '1:704124013106:android:32abf1a26469820d2c4a2b',
    messagingSenderId: '704124013106',
    projectId: 'abhayam-iej12s',
    storageBucket: 'abhayam-iej12s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq9nzD1LINX50Fst_dnKGl54ukOkq6OrU',
    appId: '1:704124013106:ios:0ab745c19b1bbcb22c4a2b',
    messagingSenderId: '704124013106',
    projectId: 'abhayam-iej12s',
    storageBucket: 'abhayam-iej12s.appspot.com',
    iosBundleId: 'com.example.abhayam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq9nzD1LINX50Fst_dnKGl54ukOkq6OrU',
    appId: '1:704124013106:ios:0ab745c19b1bbcb22c4a2b',
    messagingSenderId: '704124013106',
    projectId: 'abhayam-iej12s',
    storageBucket: 'abhayam-iej12s.appspot.com',
    iosBundleId: 'com.example.abhayam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5bIXmThn_waxcS6H95FB3Kzn5ODqLT8I',
    appId: '1:704124013106:web:c4a7f0e89fb5089d2c4a2b',
    messagingSenderId: '704124013106',
    projectId: 'abhayam-iej12s',
    authDomain: 'abhayam-iej12s.firebaseapp.com',
    storageBucket: 'abhayam-iej12s.appspot.com',
  );
}
